--
-- PostgreSQL database dump
--

\restrict 4C9IBnEVIbhTofutKfZyiHzaQ4muCH8FSsnf1dQ0wKFeNMFf98SkvdbqxeRnyGd

-- Dumped from database version 14.19 (Debian 14.19-1.pgdg13+1)
-- Dumped by pg_dump version 14.19 (Debian 14.19-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: conta_financeira; Type: TABLE; Schema: public; Owner: tesourario
--

CREATE TABLE public.conta_financeira (
    saldo_atual numeric(38,2) NOT NULL,
    id bigint NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE public.conta_financeira OWNER TO tesourario;

--
-- Name: conta_financeira_id_seq1; Type: SEQUENCE; Schema: public; Owner: tesourario
--

ALTER TABLE public.conta_financeira ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conta_financeira_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: conta_financeira; Type: TABLE DATA; Schema: public; Owner: tesourario
--

COPY public.conta_financeira (saldo_atual, id, nome) FROM stdin;
19209.95	1	BANCO CORA
\.


--
-- Name: conta_financeira_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: tesourario
--

SELECT pg_catalog.setval('public.conta_financeira_id_seq1', 1, false);


--
-- Name: conta_financeira conta_financeira_pkey; Type: CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.conta_financeira
    ADD CONSTRAINT conta_financeira_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 4C9IBnEVIbhTofutKfZyiHzaQ4muCH8FSsnf1dQ0wKFeNMFf98SkvdbqxeRnyGd

