--
-- PostgreSQL database dump
--

\restrict XjIU2n6qfyhdYynU7zKke0RnqnNfectL644Ul3wMzlYTpog7VQSvLCdQ7l1SNJt

-- Dumped from database version 14.19 (Debian 14.19-1.pgdg13+1)
-- Dumped by pg_dump version 14.19 (Debian 14.19-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cobrancas; Type: TABLE; Schema: public; Owner: tesourario
--

CREATE TABLE public.cobrancas (
    data_pagamento date,
    data_vencimento date NOT NULL,
    valor numeric(38,2) NOT NULL,
    fornecedor_id bigint,
    grupo_mensalidade_id bigint,
    id bigint NOT NULL,
    rubrica_id bigint,
    socio_id bigint,
    transacao_id bigint,
    descricao character varying(255),
    pagador character varying(255),
    status character varying(255) NOT NULL,
    tipo_cobranca character varying(255) NOT NULL,
    tipo_movimento character varying(255) NOT NULL,
    ano_lancamento integer,
    mes_lancamento integer,
    CONSTRAINT cobrancas_status_check CHECK (((status)::text = ANY (ARRAY[('ABERTA'::character varying)::text, ('PAGA'::character varying)::text, ('VENCIDA'::character varying)::text, ('CANCELADA'::character varying)::text, ('QUITADA'::character varying)::text]))),
    CONSTRAINT cobrancas_tipo_cobranca_check CHECK (((tipo_cobranca)::text = ANY (ARRAY[('MENSALIDADE'::character varying)::text, ('OUTRAS_RUBRICAS'::character varying)::text, ('AVULSA'::character varying)::text]))),
    CONSTRAINT cobrancas_tipo_movimento_check CHECK (((tipo_movimento)::text = ANY (ARRAY[('ENTRADA'::character varying)::text, ('SAIDA'::character varying)::text])))
);


ALTER TABLE public.cobrancas OWNER TO tesourario;

--
-- Name: cobrancas_id_seq1; Type: SEQUENCE; Schema: public; Owner: tesourario
--

ALTER TABLE public.cobrancas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cobrancas_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contas_pagar; Type: TABLE; Schema: public; Owner: tesourario
--

CREATE TABLE public.contas_pagar (
    data_pagamento date,
    data_vencimento date NOT NULL,
    valor numeric(38,2) NOT NULL,
    fornecedor_id bigint,
    id bigint NOT NULL,
    rubrica_id bigint NOT NULL,
    descricao character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT contas_pagar_status_check CHECK (((status)::text = ANY (ARRAY[('ABERTA'::character varying)::text, ('PAGA'::character varying)::text, ('CANCELADA'::character varying)::text])))
);


ALTER TABLE public.contas_pagar OWNER TO tesourario;

--
-- Data for Name: cobrancas; Type: TABLE DATA; Schema: public; Owner: tesourario
--

COPY public.cobrancas (data_pagamento, data_vencimento, valor, fornecedor_id, grupo_mensalidade_id, id, rubrica_id, socio_id, transacao_id, descricao, pagador, status, tipo_cobranca, tipo_movimento, ano_lancamento, mes_lancamento) FROM stdin;
\N	2025-08-10	135.00	\N	1	248	\N	31	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
\N	2025-08-10	145.00	\N	2	251	\N	10	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
\N	2025-08-10	145.00	\N	2	253	\N	21	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
\N	2025-08-10	80.00	\N	4	255	\N	1	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
\N	2025-08-10	135.00	\N	1	271	\N	45	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
\N	2025-08-10	80.00	\N	4	277	\N	44	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
\N	2025-08-10	135.00	\N	1	282	\N	54	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-03	2025-08-03	145.00	\N	\N	111	16	21	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-05	2025-08-05	25.00	\N	\N	115	5	17	\N	parcela mensalidade	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
\N	2025-08-03	640.00	\N	\N	133	16	\N	\N	Promoção Rifa Passeio	\N	ABERTA	AVULSA	ENTRADA	\N	\N
\N	2025-08-24	20.00	\N	\N	143	20	27	\N	DIZIMO	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
\N	2025-08-10	180.00	8	\N	296	11	\N	129	Pgto QR Code Pix - M. DOS R. ALENCAR DE CARVALHO	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-30	2025-08-17	87.00	\N	\N	148	5	36	\N	Manutenção Mensal	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-05	2025-08-10	75.00	\N	5	263	\N	43	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-01	2025-08-10	75.00	\N	5	247	\N	29	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-04	2025-08-03	1250.00	\N	\N	114	16	17	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-05	2025-08-10	135.00	\N	1	272	\N	15	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-28	2025-08-28	1234.00	4	\N	290	31	\N	109	Transf Pix enviada - MORAIS & SILVA CONFECCOES LTDA	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-04	2025-08-10	135.00	\N	1	283	\N	47	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-04	2025-08-03	1000.00	\N	\N	113	16	2	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-04	2025-08-10	145.00	\N	2	278	\N	27	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-02	2025-08-02	850.00	\N	\N	109	16	12	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-02	2025-08-10	50.00	\N	10	259	\N	40	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-05	2025-08-10	135.00	\N	1	262	\N	17	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-01	2025-08-10	135.00	\N	1	267	\N	11	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-01	2025-08-10	145.00	\N	2	268	\N	12	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-01	2025-08-10	55.00	\N	7	250	\N	37	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-01	2025-08-10	165.00	\N	8	264	\N	8	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-01	2025-08-10	135.00	\N	1	256	\N	5	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-01	2025-08-02	3700.00	\N	\N	110	5	8	\N	Deposito valor errado	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-01	2025-08-10	75.00	\N	5	281	\N	9	\N	Mensalidade referente ao mês de 8/2025	\N	ABERTA	MENSALIDADE	ENTRADA	\N	\N
2025-08-25	2025-08-25	44.54	\N	\N	291	14	10	110	Transf Pix enviada - ALAN SERVIO ARAUJO	ALAN SERVIO DE ARAUJO	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-21	2025-08-21	557.00	6	\N	292	14	\N	114	Transf Pix enviada - J F DE BRITO NETO CONSTRUCOES LTDA	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-21	2025-08-21	450.00	5	\N	293	14	\N	113	Transf Pix enviada - Sabina Maria Felix dos Santos	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-20	2025-08-20	119.09	\N	\N	294	30	8	115	Transf Pix enviada - SERGE ERIC PITTET	SERGE ERIC PITTET	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-14	2025-08-10	80.00	\N	4	280	\N	34	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-14	2025-08-10	80.00	\N	4	276	\N	16	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-12	2025-08-10	165.00	\N	8	265	\N	2	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-12	2025-08-10	135.00	\N	1	258	\N	19	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-12	2025-08-10	150.00	\N	11	254	\N	38	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-11	2025-08-10	150.00	\N	11	252	\N	7	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-11	2025-08-10	150.00	\N	11	284	\N	60	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-11	2025-08-10	90.00	\N	12	275	\N	25	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-11	2025-08-10	90.00	\N	12	260	\N	6	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-11	2025-08-10	90.00	\N	12	249	\N	4	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-10	2025-08-10	50.00	\N	10	273	\N	22	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-10	2025-08-10	125.00	\N	13	261	\N	46	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-10	2025-08-10	125.00	\N	13	274	\N	41	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-10	2025-08-10	145.00	\N	2	266	\N	3	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-10	2025-08-10	145.00	\N	2	269	\N	13	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-08	2025-08-10	90.00	\N	12	279	\N	20	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-19	2025-08-19	504.00	7	\N	295	29	\N	116	Boleto pago - Centro Espirita Beneficente Uniao Do Vegetal Nucle	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-10	2025-08-10	180.00	8	\N	297	28	\N	129	Pgto QR Code Pix - M. DOS R. ALENCAR DE CARVALHO	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-08	2025-08-03	40.00	\N	\N	139	16	62	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-07	2025-08-03	290.00	\N	\N	138	16	21	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-05	2025-08-03	320.00	\N	\N	137	16	10	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-04	2025-08-03	150.00	\N	\N	136	16	47	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-03	2025-09-20	1490.00	\N	\N	286	16	21	\N	PROMOCAO PASSEIO 1490	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-03	2025-08-03	700.00	\N	\N	135	16	62	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-03	2025-08-03	640.00	\N	\N	134	16	62	\N	Promoção Rifa Passeio	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-05	2025-09-20	5.00	\N	\N	287	5	17	\N	Mensalidade	\N	ABERTA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-30	2025-08-30	73.80	2	\N	288	14	\N	107	Pgto QR Code Pix - COMERCIAL CABOCLO LTDA	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-07	2025-08-07	150.00	9	\N	298	27	\N	133	Transf Pix enviada - Sara Maria De Araujo Santos	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-03	2025-08-03	472.18	1	\N	299	13	\N	144	Pgto QR Code Pix - EQUATORIAL PIAUI DISTRIBUIDORA DE ENERGIA S.A	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-03	2025-08-03	133.00	10	\N	300	26	\N	145	Transf Pix enviada - INGRID MATOS ALMEIDA	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-01	2025-08-01	9.90	11	\N	301	10	\N	151	Tarifa de saque - Cora SCFI	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-01	2025-08-01	3700.00	\N	\N	302	22	8	153	Transf Pix enviada - SERGE ERIC PITTET	SERGE ERIC PITTET	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-01	2025-08-01	350.00	12	\N	303	23	\N	152	Saque no dÃ©bito - TECBAN-SUP MATEUS MIX     -	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-01	2025-08-01	1201.08	3	\N	304	9	\N	155	Boleto pago - Cebudv Tesouraria Geral	\N	ABERTA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-30	2025-08-24	30.00	\N	\N	145	20	27	\N	DIZIMO	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-30	2025-08-24	20.00	\N	\N	144	21	27	\N	JANTAR	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-30	2025-08-10	40.00	\N	9	270	\N	33	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-30	2025-08-10	145.00	\N	2	257	\N	36	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-30	2025-08-10	50.00	\N	10	246	\N	26	\N	Mensalidade referente ao mês de 8/2025	\N	PAGA	MENSALIDADE	ENTRADA	\N	\N
2025-08-30	2025-09-20	77.00	\N	\N	285	5	36	\N	Manutenção Mensal	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-30	2025-08-30	73.80	2	\N	1	11	\N	107	Pgto QR Code Pix - COMERCIAL CABOCLO LTDA	\N	PAGA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-29	2025-08-29	1151.94	3	\N	289	9	\N	108	Boleto pago - Cebudv Tesouraria Geral	\N	PAGA	OUTRAS_RUBRICAS	SAIDA	\N	\N
2025-08-25	2025-09-17	300.00	\N	\N	142	16	63	\N	Promoção Rifa Passeio	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-24	2025-08-24	200.00	\N	\N	141	19	27	\N	COMPRA CAMISAS	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-13	2025-09-17	510.00	\N	\N	146	18	9	\N	REPASSE MESALIDADE	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-18	2025-08-03	100.00	\N	\N	140	16	10	\N	Promoção Rifa Passeio	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-17	2025-08-14	20.00	\N	\N	147	21	8	\N	JANTAR	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-12	2025-08-06	218.00	\N	\N	129	17	2	\N	DOAÇÃO BILHETE 	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
2025-08-08	2025-08-05	150.00	\N	\N	122	16	11	\N	parcela mensalidade	\N	PAGA	OUTRAS_RUBRICAS	ENTRADA	\N	\N
\.


--
-- Data for Name: contas_pagar; Type: TABLE DATA; Schema: public; Owner: tesourario
--

COPY public.contas_pagar (data_pagamento, data_vencimento, valor, fornecedor_id, id, rubrica_id, descricao, status) FROM stdin;
\.


--
-- Name: cobrancas_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: tesourario
--

SELECT pg_catalog.setval('public.cobrancas_id_seq1', 1, true);


--
-- Name: cobrancas cobrancas_pkey; Type: CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.cobrancas
    ADD CONSTRAINT cobrancas_pkey PRIMARY KEY (id);


--
-- Name: cobrancas fk_cobrancas_fornecedor; Type: FK CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.cobrancas
    ADD CONSTRAINT fk_cobrancas_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id);


--
-- Name: cobrancas fk_cobrancas_grupo_mensalidade; Type: FK CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.cobrancas
    ADD CONSTRAINT fk_cobrancas_grupo_mensalidade FOREIGN KEY (grupo_mensalidade_id) REFERENCES public.grupo_mensalidade(id);


--
-- Name: cobrancas fk_cobrancas_rubrica; Type: FK CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.cobrancas
    ADD CONSTRAINT fk_cobrancas_rubrica FOREIGN KEY (rubrica_id) REFERENCES public.rubricas(id);


--
-- Name: cobrancas fk_cobrancas_socio; Type: FK CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.cobrancas
    ADD CONSTRAINT fk_cobrancas_socio FOREIGN KEY (socio_id) REFERENCES public.socios(id);


--
-- Name: cobrancas fk_cobrancas_transacao; Type: FK CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.cobrancas
    ADD CONSTRAINT fk_cobrancas_transacao FOREIGN KEY (transacao_id) REFERENCES public.transacoes(id);


--
-- Name: contas_pagar fkf61n7454tcwwqsao0qibsfvbm; Type: FK CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.contas_pagar
    ADD CONSTRAINT fkf61n7454tcwwqsao0qibsfvbm FOREIGN KEY (fornecedor_id) REFERENCES public.fornecedores(id);


--
-- Name: contas_pagar fkott3dr9w6jb6bd00oeo4r64vs; Type: FK CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.contas_pagar
    ADD CONSTRAINT fkott3dr9w6jb6bd00oeo4r64vs FOREIGN KEY (rubrica_id) REFERENCES public.rubricas(id);


--
-- PostgreSQL database dump complete
--

\unrestrict XjIU2n6qfyhdYynU7zKke0RnqnNfectL644Ul3wMzlYTpog7VQSvLCdQ7l1SNJt

