--
-- PostgreSQL database dump
--

\restrict QWSGtAgrlmB7aSLc02hOBQUJuNnlTQRdfzYG6lud5FjKqrM7NcyeCrjh87B7j2L

-- Dumped from database version 14.19 (Debian 14.19-1.pgdg13+1)
-- Dumped by pg_dump version 14.19 (Debian 14.19-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: transacoes; Type: TABLE; Schema: public; Owner: tesourario
--

CREATE TABLE public.transacoes (
    data date,
    valor numeric(38,2),
    id bigint NOT NULL,
    relacionado_id bigint,
    descricao character varying(255),
    documento character varying(255),
    fornecedor_ou_socio character varying(255),
    lancado character varying(255),
    tipo character varying(255),
    tipo_relacionamento character varying(255),
    fornecedor_id bigint,
    status_identificacao character varying(255),
    CONSTRAINT transacoes_lancado_check CHECK (((lancado)::text = ANY (ARRAY[('LANCADO'::character varying)::text, ('NAOLANCADO'::character varying)::text]))),
    CONSTRAINT transacoes_status_identificacao_check CHECK (((status_identificacao)::text = ANY (ARRAY[('IDENTIFICADO'::character varying)::text, ('PENDENTE_REVISAO'::character varying)::text, ('NAO_ENCONTRADO'::character varying)::text]))),
    CONSTRAINT transacoes_tipo_check CHECK (((tipo)::text = ANY (ARRAY[('CREDITO'::character varying)::text, ('DEBITO'::character varying)::text]))),
    CONSTRAINT transacoes_tipo_relacionamento_check CHECK (((tipo_relacionamento)::text = ANY (ARRAY[('SOCIO'::character varying)::text, ('FORNECEDOR'::character varying)::text, ('NAO_ENCONTRADO'::character varying)::text])))
);


ALTER TABLE public.transacoes OWNER TO tesourario;

--
-- Name: transacoes_id_seq1; Type: SEQUENCE; Schema: public; Owner: tesourario
--

ALTER TABLE public.transacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transacoes_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transacoes_pendentes; Type: TABLE; Schema: public; Owner: tesourario
--

CREATE TABLE public.transacoes_pendentes (
    id bigint NOT NULL,
    arquivo_origem character varying(255),
    data date NOT NULL,
    data_importacao date NOT NULL,
    descricao character varying(500),
    documento character varying(100),
    fornecedor_ou_socio character varying(255),
    processado boolean NOT NULL,
    tipo character varying(255) NOT NULL,
    valor numeric(10,2) NOT NULL,
    CONSTRAINT transacoes_pendentes_tipo_check CHECK (((tipo)::text = ANY (ARRAY[('CREDITO'::character varying)::text, ('DEBITO'::character varying)::text])))
);


ALTER TABLE public.transacoes_pendentes OWNER TO tesourario;

--
-- Data for Name: transacoes; Type: TABLE DATA; Schema: public; Owner: tesourario
--

COPY public.transacoes (data, valor, id, relacionado_id, descricao, documento, fornecedor_ou_socio, lancado, tipo, tipo_relacionamento, fornecedor_id, status_identificacao) FROM stdin;
2025-08-28	-1234.00	109	4	Transf Pix enviada	46296293000105	MORAIS & SILVA CONFECCOES LTDA	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-25	-44.54	110	10	Transf Pix enviada	65584694304	ALAN SERVIO ARAUJO	NAOLANCADO	DEBITO	SOCIO	\N	\N
2025-08-21	-557.00	114	6	Transf Pix enviada	31434674000128	J F DE BRITO NETO CONSTRUCOES LTDA	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-21	-450.00	113	5	Transf Pix enviada	03212397330	Sabina Maria Felix dos Santos	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-20	-119.09	115	8	Transf Pix enviada	01196204489	SERGE ERIC PITTET	NAOLANCADO	DEBITO	SOCIO	\N	\N
2025-08-19	-504.00	116	7	Boleto pago	01436224000103	Centro Espirita Beneficente Uniao Do Vegetal Nucle	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-10	-180.00	129	8	Pgto QR Code Pix	16926583000116	M. DOS R. ALENCAR DE CARVALHO	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-07	-150.00	133	9	Transf Pix enviada	39427692391	Sara Maria De Araujo Santos	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-03	-472.18	144	1	Pgto QR Code Pix	06840748000189	EQUATORIAL PIAUI DISTRIBUIDORA DE ENERGIA S.A	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-03	-133.00	145	10	Transf Pix enviada	67076076349	INGRID MATOS ALMEIDA	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-01	-9.90	151	11	Tarifa de saque	37880206000163	Cora SCFI	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-01	-3700.00	153	8	Transf Pix enviada	01196204489	SERGE ERIC PITTET	NAOLANCADO	DEBITO	SOCIO	\N	\N
2025-08-01	-350.00	152	12	Saque no dÃ©bito	\N	TECBAN-SUP MATEUS MIX     -	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-01	-1201.08	155	3	Boleto pago	05899588000180	Cebudv Tesouraria Geral	NAOLANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-08	40.00	130	62	Transf Pix recebida	67076076349	INGRID MATOS ALMEIDA	NAOLANCADO	CREDITO	SOCIO	\N	PENDENTE_REVISAO
2025-08-07	290.00	134	21	Transf Pix recebida	00953527328	TALINE MACHADO MACIEL ARAUJO	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-05	320.00	135	10	Transf Pix recebida	65584694304	ALAN SERVIO DE ARAUJO	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-04	135.00	140	47	Transf Pix recebida	52984842200	WESLEY RICARDO ROCHA CALIMAN	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-04	1000.00	137	2	Transf Pix recebida	93102615287	EMANUEL LUIS DE MESSIAS ALVES	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-04	145.00	139	27	Transf Pix recebida	03632192260	ANGELA DE OLIVEIRA BONFIM CALIMAN	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-04	1250.00	141	17	Transf Pix recebida	01533562350	MARY ROSE DOS SANTOS VASCONCELOS	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-03	1490.00	146	21	Transf Pix recebida	00953527328	TALINE MACHADO MACIEL ARAUJO	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-03	700.00	142	62	Transf Pix recebida	67076076349	INGRID MATOS ALMEIDA	NAOLANCADO	CREDITO	SOCIO	\N	PENDENTE_REVISAO
2025-08-03	640.00	143	62	Transf Pix recebida	67076076349	INGRID MATOS ALMEIDA	NAOLANCADO	CREDITO	SOCIO	\N	PENDENTE_REVISAO
2025-08-02	50.00	147	40	Transf Pix recebida	30151147353	MARIA DOS NAVEGANTES GOUVEIA	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-05	350.00	136	17	Transf Pix recebida	01533562350	MARY ROSE DOS SANTOS VASCONCELOS	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-01	200.00	150	12	Transf Pix recebida	02184067385	BRENO AGUIAR FREITAS	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-01	150.00	149	29	Transf Pix recebida	d9000718-86cf-428a-8e6f-f788eec4d91d	DEYRES KENNIA LIMA SOARES	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-04	150.00	138	47	Transf Pix recebida	52984842200	WESLEY RICARDO ROCHA CALIMAN	NAOLANCADO	CREDITO	SOCIO	\N	PENDENTE_REVISAO
2025-08-30	312.00	106	36	Transf Pix recebida	02099944369	LAURA FELIZARDO SOARES DE OLIVEIRA ARAUJO	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-30	-73.80	107	2	Pgto QR Code Pix	69625903000164	COMERCIAL CABOCLO LTDA	LANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-29	-1151.94	108	3	Boleto pago	05899588000180	Cebudv Tesouraria Geral	LANCADO	DEBITO	FORNECEDOR	\N	\N
2025-08-24	200.00	112	27	Transf Pix recebida	03632192260	ANGELA DE OLIVEIRA BONFIM CALIMAN	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-13	510.00	121	9	Transf Pix recebida	93269110391	ADEMAR DAMASCENO SOARES	LANCADO	CREDITO	SOCIO	\N	PENDENTE_REVISAO
2025-08-18	100.00	117	10	Transf Pix recebida	65584694304	ALAN SERVIO DE ARAUJO	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-17	20.00	118	8	Transf Pix recebida	01196204489	SERGE ERIC PITTET	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-14	80.00	120	34	Transf Pix recebida	61918496307	JOAO VICTOR MACIEL FERREIRA GOMES	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-14	80.00	119	16	Transf Pix recebida	02658901364	MARINA CANDIDA DE LIMA BENTO	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-12	518.00	123	2	Transf Pix recebida	93102615287	EMANUEL LUIS DE MESSIAS ALVES	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-12	150.00	122	38	Transf Pix recebida	00718760301	LIA RAKEL ROCHA DE OLIVEIRA	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-11	300.00	125	7	Transf Pix recebida	97164259100	RACHEL MENDONÇA DIAS ALVES	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-11	270.00	124	4	Transf Pix recebida	15543870353	JOSÉ MARQUES MACIEL	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-10	50.00	126	22	Transf Pix recebida	86173650215	VANESSA SOUZA DE OLIVEIRA	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-10	250.00	128	46	Transf Pix recebida	01363641360	THOMPSOM THAUZER RODRIGUES DE ARAÚJO	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-10	290.00	127	3	Transf Pix recebida	80822193353	MARCELO DE CARVALHO FILGUEIRAS	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-08	150.00	132	11	Transf Pix recebida	25188562855	ALEXANDRE KEMENES	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-08	90.00	131	20	Transf Pix recebida	39427692391	SARA MARIA DE ARAÚJO SANTOS	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-02	850.00	148	12	Transf Pix recebida	02184067385	BRENO AGUIAR FREITAS	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-01	135.00	154	11	Transf Pix recebida	25188562855	ALEXANDRE KEMENES	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-01	4000.00	156	8	Transf Pix recebida	01196204489	SERGE ERIC PITTET	NAOLANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-30	50.00	105	27	Transf Pix recebida	03632192260	ANGELA DE OLIVEIRA BONFIM CALIMAN	LANCADO	CREDITO	SOCIO	\N	IDENTIFICADO
2025-08-25	300.00	111	63	Transf Pix recebida	60108877396	PLAUGUS D´ITALO DE SOUSA ALMEIDA	LANCADO	CREDITO	SOCIO	\N	PENDENTE_REVISAO
\.


--
-- Data for Name: transacoes_pendentes; Type: TABLE DATA; Schema: public; Owner: tesourario
--

COPY public.transacoes_pendentes (id, arquivo_origem, data, data_importacao, descricao, documento, fornecedor_ou_socio, processado, tipo, valor) FROM stdin;
\.


--
-- Name: transacoes_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: tesourario
--

SELECT pg_catalog.setval('public.transacoes_id_seq1', 1, false);


--
-- Name: transacoes transacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: tesourario
--

ALTER TABLE ONLY public.transacoes
    ADD CONSTRAINT transacoes_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict QWSGtAgrlmB7aSLc02hOBQUJuNnlTQRdfzYG6lud5FjKqrM7NcyeCrjh87B7j2L

