apiVersion: v1
kind: ConfigMap
metadata:
  name: db-proxy-config
data:
  haproxy.cfg: |
    global
        daemon
        maxconn 256

    defaults
        mode tcp
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    listen postgres
        bind *:5432
        mode tcp
        server postgresql-external host.docker.internal:5432 check
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-proxy-deployment
  labels:
    app: db-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-proxy
  template:
    metadata:
      labels:
        app: db-proxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.4
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: haproxy-config
        configMap:
          name: db-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: db-proxy
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP