apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesouraria-deployment
  labels:
    app: tesouraria
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tesouraria
  template:
    metadata:
      labels:
        app: tesouraria
    spec:
      containers:
        - name: tesouraria
          image: tesouraria:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tesouraria-service
spec:
  selector:
    app: tesouraria
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
